// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('create-question', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('create-question', async function() {
    await driver.get("https://eexam-five.vercel.app/dashboard")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.linkText("Questions")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".create-examiner-button")).click()
    await driver.findElement(By.id("subject")).click()
    {
      const dropdown = await driver.findElement(By.id("subject"))
      await dropdown.findElement(By.xpath("//option[. = 'Add New Subject']")).click()
    }
    await driver.findElement(By.css(".input-field:nth-child(1)")).click()
    await driver.findElement(By.css(".input-field:nth-child(1)")).sendKeys("HM303")
    await driver.findElement(By.css(".input-field:nth-child(5)")).click()
    await driver.findElement(By.css(".input-field:nth-child(1)")).click()
    await driver.findElement(By.css(".input-field:nth-child(1)")).sendKeys("SC303")
    await driver.findElement(By.css(".input-field:nth-child(5)")).click()
    await driver.findElement(By.css(".input-field:nth-child(5)")).sendKeys("3+2")
    await driver.findElement(By.id("points")).sendKeys("1")
    await driver.findElement(By.id("points")).click()
    await driver.findElement(By.id("points")).sendKeys("2")
    await driver.findElement(By.id("points")).click()
    await driver.findElement(By.id("numOptions")).sendKeys("3")
    await driver.findElement(By.id("numOptions")).click()
    await driver.findElement(By.id("numOptions")).sendKeys("2")
    await driver.findElement(By.id("numOptions")).click()
    await driver.findElement(By.css(".option-input:nth-child(1) > .input-field")).click()
    await driver.findElement(By.id("points")).sendKeys("3")
    await driver.findElement(By.id("points")).click()
    await driver.findElement(By.css(".option-input:nth-child(1) > .input-field")).click()
    await driver.findElement(By.css(".option-input:nth-child(1) > .input-field")).sendKeys("3")
    await driver.findElement(By.css(".option-input:nth-child(2) > .input-field")).click()
    await driver.findElement(By.css(".option-input:nth-child(2) > .input-field")).sendKeys("5")
    await driver.findElement(By.css(".input-field-select-field")).click()
    {
      const dropdown = await driver.findElement(By.css(".input-field-select-field"))
      await dropdown.findElement(By.xpath("//option[. = 'Easy']")).click()
    }
    await driver.findElement(By.css(".add-question-button")).click()
    await driver.findElement(By.css(".option-input:nth-child(2) > .option-input-input")).click()
    await driver.findElement(By.css(".add-question-button")).click()
  })
})
