// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create Examiner', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create Examiner', async function() {
    await driver.get("https://eexam-five.vercel.app/admin")
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    await driver.findElement(By.linkText("Examiner")).click()
    await driver.findElement(By.css(".create-examiner-button")).click()
    await driver.findElement(By.id("firstname")).click()
    await driver.findElement(By.id("firstname")).sendKeys("Harshali")
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("Harshali_20")
    await driver.findElement(By.id("middlename")).click()
    await driver.findElement(By.id("middlename")).sendKeys("Binal")
    await driver.findElement(By.id("lastname")).click()
    await driver.findElement(By.id("lastname")).sendKeys("Dharmik")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("202201214@daiict.ac.in")
    await driver.findElement(By.id("mobileno")).click()
    await driver.findElement(By.id("mobileno")).sendKeys("7600051765")
    await driver.findElement(By.id("dob")).click()
    await driver.findElement(By.id("dob")).sendKeys("2024-07-20")
    await driver.findElement(By.id("dob")).click()
    await driver.findElement(By.id("dob")).sendKeys("0002-07-20")
    await driver.findElement(By.id("dob")).sendKeys("0020-07-20")
    await driver.findElement(By.id("dob")).sendKeys("0200-07-20")
    await driver.findElement(By.id("dob")).sendKeys("2004-07-20")
    await driver.findElement(By.css(".radio-group-div > input:nth-child(2)")).click()
    await driver.findElement(By.css(".submit-btn")).click()
  })
})
