// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('delete student', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('delete student', async function() {
    await driver.get("https://eexam-five.vercel.app/admin")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".examiner-card:nth-child(3) button:nth-child(1)")).click()
  })
})
