// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('reset password', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('reset password', async function() {
    await driver.get("https://eexam-five.vercel.app/dashboard")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.linkText("Profile")).click()
    await driver.findElement(By.id("reset-button")).click()
    await driver.findElement(By.id("currentPassword")).click()
    await driver.findElement(By.id("currentPassword")).sendKeys("mFz8JhwG")
    await driver.findElement(By.id("newPassword")).click()
    await driver.findElement(By.id("newPassword")).sendKeys("gunjan_1234")
    await driver.findElement(By.id("confirmPassword")).click()
    await driver.findElement(By.id("confirmPassword")).sendKeys("gunjan_1234")
    await driver.findElement(By.css(".reset-button")).click()
  })
})
