// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('student', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('student', async function() {
    await driver.get("https://eexam-five.vercel.app/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".cta-btn")).click()
    await driver.findElement(By.id("username")).sendKeys("202200001")
    await driver.findElement(By.id("password")).sendKeys("123456789")
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("202200003")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Jughx58t")
    await driver.findElement(By.css(".login-button")).click()
  })
})
