// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Student-Login-LogOut', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Student-Login-LogOut', async function() {
    await driver.get("https://eexam-five.vercel.app/")
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("202200004")
    await driver.findElement(By.css(".eye-button > img")).click()
    await driver.findElement(By.css(".eye-button > img")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("cWwsQF3B")
    await driver.findElement(By.css(".eye-button > img")).click()
    await driver.findElement(By.css(".eye-button > img")).click()
    await driver.findElement(By.css(".eye-button")).click()
    await driver.findElement(By.css(".login-button")).click()
    {
      const element = await driver.findElement(By.css(".login-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".profile-image")).click()
    await driver.findElement(By.xpath("(//button[@id=\'reset-button\'])[2]")).click()
    await driver.findElement(By.css(".logout")).click()
  })
})
