// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Update_Examiner_Details', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Update_Examiner_Details', async function() {
    await driver.get("https://eexam-five.vercel.app/admin")
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    await driver.findElement(By.linkText("Examiner")).click()
    await driver.findElement(By.css(".examiner-card:nth-child(3) button:nth-child(2)")).click()
    await driver.findElement(By.name("middlename")).click()
    await driver.findElement(By.name("middlename")).sendKeys("Binalkumar")
    await driver.findElement(By.name("mobileno")).click()
    await driver.findElement(By.name("mobileno")).sendKeys("7600052915")
    await driver.findElement(By.name("dob")).click()
    await driver.findElement(By.name("dob")).sendKeys("2004-07-01")
    await driver.findElement(By.name("dob")).sendKeys("2004-07-18")
    await driver.findElement(By.id("save-button")).click()
  })
})
