// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('update student', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('update student', async function() {
    await driver.get("https://eexam-five.vercel.app/admin")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".examiner-card:nth-child(7) button:nth-child(2)")).click()
    await driver.findElement(By.name("mobileno")).click()
    await driver.findElement(By.name("mobileno")).sendKeys("9313891419")
    await driver.findElement(By.name("dob")).click()
    await driver.findElement(By.name("dob")).sendKeys("2024-11-01")
    await driver.findElement(By.name("dob")).sendKeys("2024-11-11")
    await driver.findElement(By.name("dob")).sendKeys("2024-01-11")
    await driver.findElement(By.name("dob")).sendKeys("2024-11-11")
    await driver.findElement(By.name("dob")).sendKeys("0002-11-11")
    await driver.findElement(By.name("dob")).sendKeys("0020-11-11")
    await driver.findElement(By.name("dob")).sendKeys("0200-11-11")
    await driver.findElement(By.name("dob")).sendKeys("2004-11-11")
    await driver.findElement(By.id("save-button")).click()
    await driver.findElement(By.name("mobileno")).click()
    await driver.findElement(By.name("mobileno")).sendKeys("8320283896")
    await driver.findElement(By.id("save-button")).click()
  })
})
