// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('View performance', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('View performance', async function() {
    await driver.get("https://eexam-five.vercel.app/dashboard")
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    await driver.findElement(By.linkText("Results")).click()
    await driver.findElement(By.css(".student-dashboard-td")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".create-examiner-button")).click()
  })
})
